### ISSUE TITLE
move reverseContourPointPen to ufoLib?

### ISSUE THREAD

**Issue by anthrotype** [typesupply/defcon#106]
That pen was originally in robofab, then copied here when we dropped the robofab dependency.

cu2qu also has a copy of the same pen, but now that the defcon one has been slightly modified (ea38ad2), the two are now out of sync with each other.

https://github.com/googlei18n/cu2qu/blob/039e35b/Lib/cu2qu/pens.py#L230-L311

I think it would make sense to move this pen to ufoLib, so everyone can use it.

**Comment by adrientetar** [comment]
sgtm

**Comment by anthrotype** [comment]
@typemytype @adrientetar now that the ReverseContourPointPen has been added to ufoLib (since v2.1.0) are you all ok with just importing it from there and remove the duplicate copy in defcon?

We can keep the current `defcon.pens.reverseContourPointPen` module for backward compatibility (like we did in fontTools when we moved the `xmlWriter`), and import the pen class from ufoLib. If a script still attempts to import it from defcon, we can issue a deprecation warning.

**Comment by typemytype** [comment]
that is fine with deprecated warning... 

slightly related: this brings back the issue of the 'old' robofab pens... https://github.com/robofab-developers/robofab/issues/52

**Comment by anthrotype** [comment]
yeah, let's revive that effort, maybe in https://github.com/robofab-developers/fontPens

in the meantime, i'll proceed with updating the defcon reverseContourPointPen module, then I'll tag a new release with that as well as your recent bugfixes on imageSet and the representation factories for composite glyphs' bounding boxes.

**Comment by justvanrossum** [comment]
I remember some discussion about moving point pens to `fontTools.pens` instead of to a new package, but I can't find it. I wonder if we ever reached a consensus. I'm slightly inclined to move that stuff to fontTools.

**Comment by anthrotype** [comment]
@justvanrossum you mean this? https://github.com/robofab-developers/robofab/issues/52#issuecomment-321212912

it looks like transition to a new package just happened. I'm fine either way
