### ISSUE TITLE
list of changed glyphs in font object

### ISSUE THREAD

**Issue by typoman** [typesupply/defcon#119]
One way of getting notifications on what glyphs has changed is to assign a "Glyph.Changed" notification to all the glyphs or assign it to the font dispatcher. While this works, there is a performance drawback. Imagine a glyph has changed which is used in other glyphs as a component. This causes all the other glyphs to be dirty and post notifications. If I want to perform a task on changed glyphs this task will be performed on all the changed glyphs one by one. But if the font was holding a list of changed glyphs after posting a "Font.Changed", I could only run this task once on all those glyphs which in some cases is less troubling. The "Font.Changed" notification could tell hold a dictionary of the parts which has changed. This could also prevent some recursive notifications in a case some parts are related to another. On another case if multiple fonts are posting "Glyph.Changed" notification, knowing which glyph belongs to which font requires to run getParent on each glyphs which is also an extra task. Is there a way to avoid these?

Thanks

**Comment by typemytype** [comment]
You could subscribe to both Font.Changed and Glyph.Changed 

In Glyph.Changed you just collect the names of glyphs that has changed 
And in the single Font.Changed notification you perform your task only on the collected changed glyphs

**Comment by adrientetar** [comment]
> knowing which glyph belongs to which font requires to run getParent on each glyphs which is also an extra task

Or glyph.font, it's just an attribute lookup.

**Comment by typoman** [comment]
All good points. Still if any notification fe: "Font.Changed" holds a dictionary of changed parts of its child fe: font.lib or glyphs it would be more convenient to deal with all the changes in one place and also could reduce number of tasks.

**Comment by adrientetar** [comment]
I can't see how this could be done without the same performance penalty as what you did yourself since notifications propagate upwards, there's one Font.Changed after each Glyph.Changed. Font.Changed notifications aren't an accumulation of multiple changes.

**Comment by typoman** [comment]
Maybe it doesn't have any effect in defcon but in usage it makes it possible to have all the information in one place. For example instead of adding multiple observers, one observer provides all the info about which part was changed. Then user could choose which part to deal with. Doesn't it make the code cleaner?

**Comment by typoman** [comment]
I also found another issue with the order of notifications in the first scenario. I realized that 'Font.Changed' posts first so if a glyph has been changed and I want to collect it through 'Glyph.Changed' and my task is executed in the 'Font.Changed', then no glyphs are collected and not task will be performed since 'Font.Changed' was posted first then the glyph was collected after in the 'Glyph.Changed'. I added the observers in different order but result was same.

**Comment by typoman** [comment]
Ok I realized that my algorithm was written before I knew how things work in defcon. Now I do only glyph related tasks in 'Glyph.Changed' and do the major task that could be heavy after 'Font.Changed' was posted and it works well. Thanks and sorry for the inconvenience.

**Comment by typoman** [comment]
Forgot to add this. 'Font.Changed' will be posted before the 'Glyph.Changed' so anyway the major task also has to be done inside the 'Glyph.Changed'. I hold off the heavy task by checking if the glyph is used as component in other glyphs then when all of them posted their notifications I perform the task. So using 'Font.Changed' in this case is not good way of making things faster.

**Comment by adrientetar** [comment]
> 'Font.Changed' will be posted before the 'Glyph.Changed' 

That's odd, normally notifications propagate upwards, i.e. Contour -> Glyph -> Layer -> LayerSet -> Font
