### ISSUE TITLE
font/layer .keys()

### ISSUE THREAD

**Issue by typemytype** [typesupply/defcon#125]
A simple example throwing a `RuntimeError: Set changed size during iteration` error

this should actually work...

```python
import defcon

f = defcon.Font()

for a in "abcd":
    f.newGlyph(a)
    
for a in f.keys(): 
    f.newGlyph("%s.sc" % a)
```

a quick solution is to pack the `set` into a `list`

**Comment by adrientetar** [comment]
I feel like this should just be list(f.keys()), I mean if you modify the glyph list that you're iterating on you should "freeze" it to a list first.

**Comment by typemytype** [comment]
I guess a font object should work very similar as a dict, it use to work like this.

```python
f = dict(a=1, b=2, c=3)

for a in f.keys(): 
    f["%s.sc" % a] = 4
```

**Comment by adrientetar** [comment]
Yea this code will fail on Python 3, same as if you're doing iterkeys() instead of keys() on Python 2.

We could make keys return a copy if running on Python 2. @anthrotype wdyt?

**Comment by typemytype** [comment]
Oke, I'm not shifted to py3

But it could be considered.

**Comment by anthrotype** [comment]
> We could make keys return a copy if running on Python 2

That's worse, IMO. It would make it more difficult to write portable py2.py3 code that uses defcon objects.
Personally, I prefer to keep the current python3 semantics (dict.keys() behaving like sets) as it feels more future proof.
That means `for a in font.keys():` should be written like `for a in list(font.keys()):`, which is the way one would write it in python3 if font was a dict.

**Comment by typemytype** [comment]
Also good, this has to be documented as this is a big change for py2 people
