### ISSUE TITLE
Simple tutorial for defcon to create TTF/OTF font requested

### ISSUE THREAD

**Issue by jamadagni** [typesupply/defcon#148]
Hello. This is an almost repost of: https://github.com/fonttools/fonttools/issues/1102 since I was redirected here from there.

I have looked through the documentation of defcon but it's largely a somewhat barebones API documentation and sparse in the matter of examples.

[This page](http://ts-defcon.readthedocs.io/en/latest/index.html) says:

> defcon is very easy to use:

and gives a supposed example:

```
from defcon import Font
font = Font()
# now do some stuff!
```

But the point is: *I am not sure how to "do some stuff"!!!*

For instance, I can see from the docs that there is a [Font.newGlyph](http://ts-defcon.readthedocs.io/en/latest/objects/font.html#defcon.Font.newGlyph) method, [Glyph.appendContour](http://ts-defcon.readthedocs.io/en/latest/objects/glyph.html#defcon.Glyph.appendContour) and [Contour.appendPoint](http://ts-defcon.readthedocs.io/en/latest/objects/contour.html#defcon.Contour.appendPoint) method. But it is not clear that these methods are the recommended way to go about creating glyphs.

Randomly browsing through the issues, the example provided under https://github.com/typesupply/defcon/issues/94 seems to indicate that we should rather get a pen and use that pen instead.

I wanted to do something like:

```
g1 = newfont.addglyph()
g1.addChar(<unicode-codepoint1>)
g1.addChar(<unicode-codepoint2>)
g1.moveTo(<p1>)
g1.quadTo(<c>,<p2>)
g1.lineTo(<p3>)
g1.closePath()
g1.moveTo(<p4>)
...
g2 = ...
...
newfont.write("myfont.ttf")

```

… which is similar to what is seen in the issue above, but that code fragment talks about something else and not exporting a simple workable font.

I would much appreciate complete instructions for at least creating a single font with a single glyph mapped to a single Unicode character and exporting it to a TTF/OTF. One can definitely take it from there.

Without a meaningful complete working example (leave alone a tutorial), it feels one is in an unknown forest without GPS for navigation! No offence, and I realize people are releasing this open-source without any guarantees or assurances, but this is just a humble request to take one simple step to make things much much easier for people like me! 🙏🙏🙏

Thank you!

**Comment by anthrotype** [comment]
everyone would love better documentation but the fact is we all have limited time/availability.

defcon can create UFO files, but it cannot compile them to OTF/TTF.

You're looking for a combination of defcon plus a font compiler that can read the source UFO data and generate a binary OpenType font. 

You can try https://github.com/googlei18n/ufo2ft which is written in pure python (and is the compiler used by the [fontmake](https://github.com/googlei18n/fontmake) tool), or the makeotf tool from Adobe's https://github.com/adobe-type-tools/afdko/ which is written in C and is used by many font editors like Glyphs, FontLab, etc.

I would love to help you more but have other things to attend to right now, sorry.
Keep browsing the source code of the above mentioned tools for examples...

**Comment by adrientetar** [comment]
~~~python
from defcon import Font
from ufo2ft import compileTTF

font = Font()

# set font metrics
font.info.unitsPerEm = 1000
font.info.ascender = 750
font.info.capHeight = 700
font.info.xHeight = 500
font.info.descender = -250

# glyph
square = Font.newGlyph("square")
square.unicode = 0x0020
pen = square.getPen()
pen.moveTo(0, 0)
pen.lineTo(0, 100)
pen.lineTo(100, 100)
pen.lineTo(100, 0)
pen.closePath()

# export
ttf = compileTTF(font)
ttf.save("MyFont.ttf")
~~~

**Comment by jamadagni** [comment]
Thank you very much for this guideline. I fixed the errors to get:

    from defcon import Font
    from ufo2ft import compileTTF

    font = Font()

    # set font metrics
    font.info.unitsPerEm = 1000
    font.info.ascender = 750
    font.info.capHeight = 700
    font.info.xHeight = 500
    font.info.descender = -250
    font.info.familyName = "MyFont"

    # glyph
    square = font.newGlyph("square")
    square.unicode = 0x0020
    pen = square.getPen()
    pen.moveTo((0, 0))
    pen.lineTo((0, 100))
    pen.lineTo((100, 100))
    pen.lineTo((100, 0))
    pen.closePath()

    # export
    ttf = compileTTF(font)
    ttf.save("MyFont.ttf")

and it successfully wrote the file with the following (harmless) warnings:

    WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
    WARNING:ufo2ft.fontInfoData:Underline position not set in UFO, defaulting to UPM * -0.075
    WARNING:ufo2ft.fontInfoData:Underline thickness not set in UFO, defaulting to UPM * 0.05
