### ISSUE TITLE
Glyph.correctContourDirection(): crash on some glyphs

### ISSUE THREAD

**Issue by madig** [typesupply/defcon#197]
1. git clone --depth=1 https://github.com/adobe-fonts/source-sans-pro.git
2. 
```Python
import defcon
u = defcon.Font("source-sans-pro/Roman/Masters/master_0/SourceSans_ExtraLight.ufo")
u["lira"].correctContourDirection()
```
Traceback:
```
c:\program files\python36\lib\site-packages\defcon\objects\glyph.py in correctContourDirection(self, trueType, segmentLength)
    645         # sort the contours by area
    646         contours = [(contour.area, contour) for contour in self]
--> 647         contours = [contour for (area, contour) in reversed(sorted(contours))]
    648         # build a tree of nested contours
    649         tree = {}

TypeError: '<' not supported between instances of 'Contour' and 'Contour'
```

**Comment by anthrotype** [comment]
that's because Contour doesn't implement `__lt__` operator, and some contour instances may well have the same area, so the second item in the tuples (i.e. the contour itself) get compared by `sorted` function.
maybe better do something like `sorted(contours, key=lambda contour: -contour.area)`

**Comment by madig** [comment]
Hm. Is it worth it to implement the `__lt__` method with an area test? Or is it better done as a one-off in `correctContourDirection`?
