### ISSUE TITLE
Make Font.save more modular

### ISSUE THREAD

**Issue by adrientetar** [typesupply/defcon#24]
So I just implemented template glyphs through a glyph.template boolean attribute and I would like to have template glyphs not saved into the UFO. 
Right now I have to copy the whole Font.save() function in my subclass to blacklist these glyphs from the glyphSet (still working with ufo2 just now, but I didn’t see any specific mechanism in the ufo3 defcon so I thought I’d open up an issue for it).

**Comment by typesupply** [comment]
Hm. I implemented support for this in the ufo3 branch. Here:

https://github.com/typesupply/defcon/blob/ufo3/Lib/defcon/objects/layer.py#L607

You could try something like:

```python

def saveGlyph(...):
    if not glyph.template:
        super(self.__class__, self).saveGlyph(...)
```

You could simulate this in the master branch by doing something like this in your Font subclass:

```python
def save(...):
    for glyph in self:
        if glyph.template:
            glyph.dirty = False
    super(self.__class__, self).save(...)
```

Marking it as not dirty would make the loop skip the glyph and therefore not save it. This might not work in save as operations. That's a tricky situation.

**Comment by adrientetar** [comment]
Thanks, Tal.
