### ISSUE TITLE
[UFO3]Assertion fail in inserting glyph

### ISSUE THREAD

**Issue by paarandika** [typesupply/defcon#30]
The code block below gives me an assertion fail when it try to insert a glyph with anchors.
```python
new_ufo = Font()
font_source = Font(fontList[0])
for glyph_name in font_source.keys():
    print glyph_name,
    glyph = font_source[glyph_name]
    new_ufo.insertGlyph(glyph)
```
Full stack trace is below
```python
Traceback (most recent call last):
  File "merger.py", line 41, in <module>
    new_ufo.insertGlyph(glyph)
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/font.py", line 198, in insertGlyph
    return self._glyphSet.insertGlyph(glyph, name=name)
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/layer.py", line 222, in insertGlyph
    dest.copyDataFromGlyph(glyph)
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/glyph.py", line 1059, in copyDataFromGlyph
    self.anchors = [self.instantiateAnchor(a) for a in glyph.anchors]
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/glyph.py", line 680, in _set_anchors
    self.appendAnchor(anchor)
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/glyph.py", line 712, in appendAnchor
    self.insertAnchor(len(self._anchors), anchor)
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/glyph.py", line 725, in insertAnchor
    assert anchor.glyph != self
AssertionError
```

**Comment by jenskutilek** [comment]
I stumbled over the same error. I'm not sure how this is supposed to work, as it's quite complex.

If I get this correctly, the line `self.anchors = [self.instantiateAnchor(a) for a in glyph.anchors]` calls the setter method for `Glyph._set_anchors`. The anchor returned by `self.instantiateAnchor` has its `glyph` attribute already set to its parent glyph, while the setter method for `Glyph.anchors` in turn uses `Glyph.appendAnchor` which specifically makes sure the supplied anchor doesn't already belong to the `Glyph` it is about to be appended to.

@typesupply, could you shed some light on how it is supposed to work? Just getting rid of the assertion in glyph.py line 725 seems to fix it, but I'm not sure about any possible side effects.

**Comment by adrientetar** [comment]
Yeah there's an assert that prevents giving one anchor to multiple glyphs at once (it was useful to me once) though indeed when you want to set them manually things can become hard. Either the instanciate method or the setter should be relaxed it seems.

**Comment by jamesgk** [comment]
I just ran into this; note also that five lines below this assertion is `assert anchor.glyph in (self, None)` so essentially the only valid value for the glyph attribute is None.
