### ISSUE TITLE
Don't validate kerning when saving to UFO

### ISSUE THREAD

**Issue by behdad** [typesupply/defcon#38]
It doesn't help.  I think a reader / writer should only fail if the file / data is structurally incorrect, not semantically.  Semantic validation should only happen by editors, generators, lint tools, etc.  This is causing us lots of trouble, specially because fontMath's kerningMath can easily generate invalid kerning right now.  I'll try to fix that, but in the mean time, I think this should also be fixed.

I actually have a better proposal: change UFO to say that if both a glyph-class and class-glyph kerning are present, then the glyph-class wins over the class-glyph one.  This way, there will be no invalid kerning whatsoever.

@jamesgk

**Comment by typesupply** [comment]
> Semantic validation should only happen by editors, generators, lint tools, etc.

Defcon doesn't qualify as an editor?

**Comment by behdad** [comment]
> Semantic validation should only happen by editors, generators, lint tools, etc.
> Defcon doesn't qualify as an editor?

No, we use it as a piece of the production pipeline; it's pulled via MutatorMath and other pieces.  We don't control the input.  Best we can do is warn user of the issues but continue to produce output.

**Comment by behdad** [comment]
Also, put another way: Imagine you open RoboFont, kern your font for five hours, but you are not done and there are still conflicts and clean ups to be done; but it's late and you rather get some sleep.  How would you feel if RoboFont refuses to save your work because you have conflicting kerning rules?

**Comment by typesupply** [comment]
> How would you feel if RoboFont refuses to save your work because you have conflicting kerning rules?

I see your point, but the alternative is that you kern for five hours, close the file, go to sleep and then wake up the next day to get back to work. You go to open your file and you are greeted with a "Nope. This file contains some data that can't be resolved." I *have* experienced this before. Many, many, many horrible times. This is why I wrote the validators. They don't exist for sadistic reasons. I don't disagree that it puts users in a rough place as they aren't responsible for ensuring that the editor doesn't have bugs. But I want a workflow where App A doesn't have to know about App B's bugs. We've done that and it doesn't end well.

I'm not opposed to changing the defcon behavior as long as it doesn't throw things into chaos. My basic goal is that I want defcon to be able to open a UFO and not have to guess about what the previous editor may have done wrong. I don't know how to resolve this one bug without introducing the possibility for a whole lot of bugs in other places. If there is a model for handling this, I'm all ears.

I don't agree that changing the spec is the answer.

**Comment by schriftgestalt** [comment]
The refusing part can just as well be put then the kerning is put into the final font. I agree with @behdad that the file format is not responsible for consistency. Or should if refuse to save outlines with wrong path direction, too?

**Comment by behdad** [comment]
> How would you feel if RoboFont refuses to save your work because you have conflicting kerning rules?
> 
> I see your point, but the alternative is that you kern for five hours, close the file, go to sleep and then wake up the next day to get back to work. You go to open your file and you are greeted with a "Nope. This file contains some data that can't be resolved."

To me, the "refuses to open" case is much better experience than "refuses to save".  Because in the case of "refuses to open", at least you have your data as an XML.  You can run validators on it, fix it manually, open in another editor, ...

> I have experienced this before. Many, many, many horrible times.

With conflicting kerning?  Sure, validating the general structure of the UFO is very very useful.  I just think this conflicting-kerning case is going to far.

> This is why I wrote the validators. They don't exist for sadistic reasons. I don't disagree that it puts users in a rough place as they aren't responsible for ensuring that the editor doesn't have bugs. But I want a workflow where App A doesn't have to know about App B's bugs. We've done that and it doesn't end well.

At least it should be warnings.  Editors can warn user that the UFO has warnings and confirm that they want to save.


> I'm not opposed to changing the defcon behavior as long as it doesn't throw things into chaos. My basic goal is that I want defcon to be able to open a UFO and not have to guess about what the previous editor may have done wrong. I don't know how to resolve this one bug without introducing the possibility for a whole lot of bugs in other places. If there is a model for handling this, I'm all ears.
> 
> I don't agree that changing the spec is the answer.

The spec change was my preferred resolution in this case, as it removes ambiguity.

**Comment by behdad** [comment]
In other words, where does ufoLib's validator end and glyph-nanny start?

**Comment by typesupply** [comment]
> Or should if refuse to save outlines with wrong path direction, too?

That's a very different thing. A conflicting kerning pair is more like one point being given two conflicting instructions about where the point should be placed.

**Comment by typesupply** [comment]
> To me, the "refuses to open" case is much better experience than "refuses to save". Because in the case of "refuses to open", at least you have your data as an XML. You can run validators on it, fix it manually, open in another editor, ...

And in the case of refusing to save, you have the undo stack and you know who is responsible for the bug. In the case of refusing to open the responsible party is "Um, someone else not me. I hope." :) They are equally crappy places for users.

> With conflicting kerning?

Probably. FontLab was a place of many mysterious crashes and errors.

Changing this makes me very nervous, but I'm getting so much push back that I'll turn it off later tonight. I really hope this isn't a slippery slope that leads to lots more cases of allowing other unresolvable data into the files.

I'm going to have to spend some time reviewing defcon's kerning internals. All of the ufo3 branch of defcon is built on the assumption that the data that has been populated to the objects has been checked for sanity and isn't going to cause problems. That may require some changes to the objects.

I'll also think about the spec change. It's not a horrible change, but it feels like, "If something did this thing wrong here is how you must resolve it. Things must not do this thing wrong, but, you know, just in case."

**Comment by adrientetar** [comment]
I don't have a strong opinion on this, but I symphatize that it might be more useful to save anyway and fix afterwards than verbiet... **maybe defcon should not fail but return a report** so that the editor can display a warning to the user "Do you want to proceed with saving?" or so.
I've had quite a few pain points with validators: trailing off curves forbidden in open contours and curve segments with onCurve marked as line forbidden (I've had reports of such files coming from Glyphsapp and FontForge...). In the latter case I'd probably leave the validator in-place (though in all cases I think those segments were meant to be actual curves... I know input data is wrong but.) but I think we could allow trailing offCurve safely (RoboFont does), you mainly need a convention of saying that it comes at the end of the contour and not before the first point.

By the way iirc I needed to patch \_get_segments a bit on the ufo3 branch to get the trailing offCurve to work, but it otherwise causes no problems afaict.

> In other words, where does ufoLib's validator end and glyph-nanny start?

Wow that escalated quickly, I mean really? Glyph nanny serves a completely different purpose.

> All of the ufo3 branch of defcon is built on the assumption that the data that has been populated to the objects has been checked for sanity and isn't going to cause problems. That may require some changes to the objects.

Maybe give the option to the user to handle it as they want, or fail by default but put an argument to change that. I mean like encode/decode in Python you can do "strict" or "ignore" that is useful I think.

Also a way to check whether the report contains a warning (e.g. duplicates) or more serious errors (e.g. bad conflicts) would be nice (maybe that's already the case, I haven't checked).

**Comment by benkiel** [comment]
> To me, the "refuses to open" case is much better experience than "refuses to save".

Neither are great, but from a lot of experience dealing with a lot of kerning, I would much rather know at save when I am in the presence of mind to remember what was done, than on open, which may be happening at a much later date (or by another person) where one may not know what has happened.

Historically, a lot of us have experience dealing with kerning going silently corrupt in ways that are very hard to untangle. This is a much different problem than an outline being wrong, and one where I favor defcon being strict in checking.

If this goes forward, I am very much in favor of fail by default with an argument to change that—with a report being returned if it would have failed.

**Comment by LettError** [comment]
> If this goes forward, I am very much in favor of fail by default with an argument to change that—with a report being returned if it would have failed.

As a method to prevent failing data from other editors floating downstream and gumming up the works, I agree.

But I have had problems with instances in MutatorMath that failed validation and then did not save because  valid pairs in the masters interpolate to conflicting combinations. MutatorMath has no recourse, it can't edit the masters to prevent the pairs, nor can the problem be detected in the masters.

It is a very practical thing: debugging an instance that exists is so much nicer than debugging one that does not exist.

**Comment by typesupply** [comment]
> I've had quite a few pain points with validators: trailing off curves forbidden in open contours and curve segments with onCurve marked as line forbidden (I've had reports of such files coming from Glyphsapp and FontForge...).

Let's discuss this in another issue. I want to keep this slippery slope dedicated to kerning.

**Comment by typesupply** [comment]
For the record, here are the lines where the validator results are evaluated:

https://github.com/typesupply/defcon/blob/4909db088e24e0058f871bd5107806b7cb5a7ca2/Lib/defcon/objects/font.py#L400

https://github.com/typesupply/defcon/blob/4909db088e24e0058f871bd5107806b7cb5a7ca2/Lib/defcon/objects/font.py#L689

https://github.com/typesupply/defcon/blob/4909db088e24e0058f871bd5107806b7cb5a7ca2/Lib/defcon/objects/font.py#L1145

I'll delete the validation and subsequent conditional error. If someone else wants to make this more nuanced, I'll be happy to review a PR.

**Comment by typesupply** [comment]
I made the change. ac81bd742a0b2f6238d59f7b4267ffe808360d44
