### ISSUE TITLE
Bring the MM kerning lookup logic to the base kerning object.

### ISSUE THREAD

**Issue by typesupply** [typesupply/defcon#4]
Make it so that looking up a kerning value uses the same logic for handling class pairs as MM does. For example:

kerning["A", "B"] would look for the following:

A B
A (group containing B)
(group containing A) B
(group containing A) (group containing B)
If nothing is found, return 0.

Would this be too much like a scripting API? It would be useful to have this logic centralized so that others don't have to invent it. (A sample implementation is in the UFO spec, though.)

If this is implemented, the groups should have representations for side 1 and side 2 glyph to class mapping.

**Comment by benkiel** [comment]
Added in https://github.com/typesupply/defcon/commit/2b6eea8cfb6b4528447b04fcb6a22a24265b205a
