### ISSUE TITLE
Standard key for sort descriptors?

### ISSUE THREAD

**Issue by adrientetar** [typesupply/defcon#40]
Is there any standard key for storing defcon sortDescriptor? I'll probably use com.defcon.sortDescriptor for now.

**Comment by typemytype** [comment]
@typesupply does this sound fine?

I can port RoboFont's lib key `com.typemytype.robofont.sort` to `com.defcon.sortDescriptor`
thanks

**Comment by typesupply** [comment]
I don't own `com.defcon` ;). Use `com.typesupply.*`.

**Comment by adrientetar** [comment]
So com.typesupply.defcon.sortDescriptor or just com.typesupply.sortDescriptor?

**Comment by typesupply** [comment]
`com.typesupply.defcon.sortDescriptor`
