### ISSUE TITLE
Unicode Data outdated

### ISSUE THREAD

**Issue by sansplomb** [typesupply/defcon#44]
Would it be possible to update the script txt to Unicode 9.0 instead of the old 5.0 ?
see:
ftp://unicode.org/Public/9.0.0/ucd/Scripts-9.0.0d17.txt

thanks,
Jérémie

**Comment by typesupply** [comment]
Yeah. I'll update them next time I'm working on defcon. The affected files will be:

- defcon/Lib/defcon/tools/unicodeTools.py
- defcon/tools/UnicodeData.txt

It should be easy to update everything.
