### ISSUE TITLE
Travis and AppVeyor for ufo3 branch tests

### ISSUE THREAD

**Issue by moyogo** [typesupply/defcon#56]
Enable Travis and AppVeyor to run tests on pull requests. Coveralls can be enabled too.

**Comment by moyogo** [comment]
@typesupply as requested in #67:
- you can activate Travis on https://travis-ci.org/typesupply/defcon
- you can add defcon as an appveyor project on https://ci.appveyor.com/projects/new

**Comment by adrientetar** [comment]
Ah oops I didn't even notice that the files were already in there. Thanks, Denis!

**Comment by typesupply** [comment]
I activated them.
