### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by khaledhosny** [typesupply/defcon#72]
Is the generated API documentation (of the `ufo3` branch mainly) hosted somewhere? If not, what about using `gh-pages` for it?

**Comment by davelab6** [comment]
http://ts-defcon.readthedocs.io/en/latest/

**Comment by khaledhosny** [comment]
This is either outdated or does not cover the `ufo3` branch.

**Comment by adrientetar** [comment]
http://ts-defcon.readthedocs.io/en/ufo3/

**Comment by khaledhosny** [comment]
I see, thanks. May be this should be made more prominent, on the README or something.
