### ISSUE TITLE
newGlyph should return the glyph.

### ISSUE THREAD

**Issue by typesupply** [typesupply/defcon#9]
Make newGlyph return the newly created glyph.

**Comment by adrientetar** [comment]
This seems to be present in ufo3 branch so I would say it can be closed. Good to have, btw.

**Comment by adrientetar** [comment]
Oops, nevermind. The function in font.py has a return but not the subfunction in layer.py so it always returns None. A simple return glyph in layer.py should fix this, I reckon.

**Comment by moyogo** [comment]
"#39 Fixes" fixed this in the ufo3 branch. Or was this for the master branch?

**Comment by typesupply** [comment]
This was for the ufo3 branch.

**Comment by moyogo** [comment]
@typesupply cool, this can be closed then ;-)
